name: flutter_demo
description: Flutter demo application for MerkleKV Mobile
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  # UI and state management
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^11.0.0
  
  # MerkleKV packages
  merkle_kv_core:
    path: ../../packages/merkle_kv_core
  
  # Utilities
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  
  # Mobile E2E testing dependencies
  device_info_plus: ^9.1.0
  network_info_plus: ^4.0.2
  battery_plus: ^4.0.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
